Makefile.GNU added XML validation; simplified making of authors.xml
2008-11-18  Ulf-D. Ehlert  <ulfehlert@svn.gnome.org>

	* Makefile.GNU
	* Makefile.am: added XML validation; simplified making of authors.xml

	* stylesheets/authors.xml
	* stylesheets/authors_text.xsl
	* stylesheets/authors_docbook.xsl: simplified making of authors.xml
	(translations in "src/preface/titles.xml" are no longer needed)

	* tools/migrate.sh: format gimp.xml; print runtime info

svn path=/branches/xml2po-support/; revision=2599

diff --git a/Makefile.GNU b/Makefile.GNU
--- a/Makefile.GNU
+++ b/Makefile.GNU
@@ -59,6 +59,7 @@ xmlpodir = xml
 htmldir  = html
 pdfdir   = pdf
 odfdir   = odf
+logdir   = log
 
 # Find files and directories
 xml_file_predicates =       \
@@ -174,11 +175,7 @@ endif
 ########################################################################
 
 first: all
-all: validate html index AUTHORS
-
-# ignore
-validate: ;
-
+all: html index AUTHORS
 
 
 ########################################################################
@@ -283,9 +280,34 @@ $(xmlpodir)/en: $(XML_FILES)
 # Special case: en
 xml-en: $(xmlpodir)/en ;
 
-# Debugging
-list-xmlfiles-en list-xml-files-en list-xml-en:
-	@echo $(en_XML_FILES)
+
+########################################################################
+####            XML validation                                      ####
+########################################################################
+
+validate: validate-en ;
+validate-%: xmllint-% ;
+xmllint: xmllint-en ;
+
+xmllint-%: $(logdir)/%-xmllint.log ;
+	@echo >&2 "Validating '$*' not implemented."
+
+xmllint-en: $(logdir)/en-xmllint.log ;
+	$(cmd) test -s $< && cat $< || echo "No errors."
+
+$(logdir)/en-xmllint.log: $(logdir) $(XML_FILES)
+	$(cmd) if type $(XMLLINT) >/dev/null 2>&1; then \
+		echo "*** Validating XML for 'en' ... "; \
+		$(XMLLINT) $(XMLLINTFLAGS) --xinclude $(xmlpodir)/en/gimp.xml \
+		| sed -e 's,xmlns:xi="http://www.w3.org/2001/XInclude",,' \
+		| $(XMLLINT) $(XMLLINTFLAGS) --nonet --valid --noout - 2>$@ \
+		|| true; \
+	else \
+		echo "*** Validating 'en' skipped: 'xmllint' not found."; \
+	fi
+
+$(logdir):
+	$(cmd) mkdir $@ && test -w $@
 
 
 ########################################################################
@@ -443,7 +465,7 @@ AUTHORS: $(AUTHORS_STYLESHEET_XML) stylesheets/authors_text.xsl $(AUTHORS_DOCBOO
 	  $< \
 	  > $@
 	
-$(AUTHORS_DOCBOOK_XML): $(AUTHORS_STYLESHEET_XML) src/preface/titles.xml stylesheets/authors_*.xsl
+$(AUTHORS_DOCBOOK_XML): $(AUTHORS_STYLESHEET_XML) stylesheets/authors_*.xsl
 	$(msg) "**** Making $@ ... "
 	$(cmd) $(XSLTPROC) \
 	  $(XSLTFLAGS) $(XSLTEXTRAFLAGS) \
diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -150,6 +150,7 @@ xmlpodir = xml
 htmldir  = html
 pdfdir   = pdf
 odfdir   = odf
+logdir   = log
 
 
 ########################################################################
@@ -191,7 +192,7 @@ AUTHORS: $(AUTHORS_STYLESHEET_XML) stylesheets/authors_text.xsl $(AUTHORS_DOCBOO
 	  $< \
 	  > $@
 	
-$(AUTHORS_DOCBOOK_XML): $(AUTHORS_STYLESHEET_XML) src/preface/titles.xml stylesheets/authors_*.xsl
+$(AUTHORS_DOCBOOK_XML): $(AUTHORS_STYLESHEET_XML) stylesheets/authors_*.xsl
 	@echo "Creating $@"
 	$(cmd) $(XSLTPROC) \
 	  $(XSLTFLAGS) \
@@ -344,6 +345,35 @@ $(xmlpodir)/en: $(XML_FILES)
 
 # Special case: en
 xml-en: $(xmlpodir)/en ;
+
+
+########################################################################
+####            XML validation                                      ####
+########################################################################
+
+validate: validate-en ;
+validate-%: xmllint-% ;
+xmllint: xmllint-en ;
+
+xmllint-%: $(logdir)/%-xmllint.log ;
+	@echo >&2 "Validating '$*' not implemented."
+
+xmllint-en: $(logdir)/en-xmllint.log ;
+	$(cmd) test -s $< && cat $< || echo "No errors."
+
+$(logdir)/en-xmllint.log: $(logdir) $(XML_FILES)
+	$(cmd) if type $(XMLLINT) >/dev/null 2>&1; then \
+		echo "*** Validating XML for 'en' ... "; \
+		$(XMLLINT) $(XMLLINTFLAGS) --xinclude $(xmlpodir)/en/gimp.xml \
+		| sed -e 's,xmlns:xi="http://www.w3.org/2001/XInclude",,' \
+		| $(XMLLINT) $(XMLLINTFLAGS) --nonet --valid --noout - 2>$@ \
+		|| true; \
+	else \
+		echo "*** Validating 'en' skipped: 'xmllint' not found."; \
+	fi
+
+$(logdir):
+	$(cmd) mkdir $@ && test -w $@
 
 
 ########################################################################
